# Numpy

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.


Numeric, the ancestor of NumPy, was developed by Jim Hugunin. Another package Numarray was also developed, having some additional functionalities. In 2005, Travis Oliphant created NumPy package by incorporating the features of Numarray into Numeric package. There are many contributors to this open source project.


###### Operations using NumPy
Using NumPy, a developer can perform the following operations –
- Mathematical and logical operations on arrays.
- Fourier transforms and routines for shape manipulation.
- Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.


In [1]:
#importing numpy as np
import numpy as np

In [2]:
#Creating a numpy array
a =np.array([[1,2,3],[4,5,6]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6]])

### Methods of Numpy 

###### 1.Shape - Returns the shape of the array

In [4]:
a.shape      #2 rows 3 columns

(2, 3)

###### 2.Size - Return total number of elements in an array

In [5]:
a.size

6

###### 3.Reshape - used to change to shape of an array.

In [6]:
a.reshape(3,2)   #this change is not saved. its temprory

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a       

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#this ways you can make change permanently
a.shape = (3,2)

In [9]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

###### 4.Transpose - Converts rows into columns and viz

In [10]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
a.T              #this is also a temprory not inplace

array([[1, 3, 5],
       [2, 4, 6]])

In [12]:
a    

array([[1, 2],
       [3, 4],
       [5, 6]])

###### 5.ndim - Returns the number of dimension of an array

In [13]:
a.ndim

2

### Funtions in Numpy

In [14]:
a = np.arange(1,7).reshape(2,3)    # this is arange function, similar to range funtion
b = np.arange(7,13).reshape(2,3)   # we will discuss about arange later

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

###### 1.Concatenate((array1,array2)) - used to join two different array

In [17]:
np.concatenate((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

###### 2.Hstack((array1,array2)) - used to concate two array horizontally

In [18]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

###### 3.Vstack((array1,array2)) - used to concate two array vertically

In [19]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

###### 4.Append(array,list.of.elements) - used to add the elements in an array

In [20]:
c = np.arange(1,7)
c

array([1, 2, 3, 4, 5, 6])

In [21]:
np.append(c,[7,8,9])     #this is also a temprory, not inplace

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
 c

array([1, 2, 3, 4, 5, 6])

###### 5.Insert(array,index,element)-  used to add element at specific index

In [23]:
d = np.arange(2,6)
d

array([2, 3, 4, 5])

In [24]:
np.insert(d,0,1)

array([1, 2, 3, 4, 5])

In [25]:
d

array([2, 3, 4, 5])

###### 6.Delete(array,list.of.elements.index)- used to delete elementof specific index

In [26]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [27]:
np.delete(a,[1,2,3]) #this will delete 2,3,4

array([1, 5])

###### That's all for now, there is much more to learn in numpy.
keep learning

# Great Job