# Numpy - Array Creation Routine

A new adarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.

In [1]:
import numpy as np

###### 1.np.empty - It creates an uninitialized array of specified shape and dtype. It uses the following constructor.

###### Syntax:-
np.empty(shape, dtype =  float, order = C)


In [2]:
x = np.empty([3,2],dtype = int)
x

array([[0, 0],
       [0, 0],
       [0, 0]])

###### 2.np.zeros – It returns a new array of specified size, filled with zeros.

###### Syntax:
np.zeros(shape, dtype =  float, order = C)


In [3]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [4]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [5]:
np.zeros(5,dtype=[('x','i4'),('y','i4')])

array([(0, 0), (0, 0), (0, 0), (0, 0), (0, 0)],
      dtype=[('x', '<i4'), ('y', '<i4')])

###### 3.np.ones – It returns new array of specified size and type, filled with ones.

###### Syntax:
np.zeros(shape, dtype =  float, order = C)

In [6]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.ones(5,dtype =int)

array([1, 1, 1, 1, 1])

In [8]:
np.ones((3,3),dtype =int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### 4.np.eye – It returns the identity matrix 

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.eye(3,dtype =int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

###### Array From Numerical Range 
###### 4 .Arange - An array of evenly spaced numbers just like pythons range function.


###### Syntax: 
np.arange(start,stop,step,dtype)

In [11]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a = np.arange(4,34,4)
a

array([ 4,  8, 12, 16, 20, 24, 28, 32])

###### 5.np.linspace() -T his function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

###### Syntax:
np.linspace( start,stop,num,endpoint,restep,dtype )

In [13]:
np.linspace(11,20,10)

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [14]:
np.linspace(10,20,5,endpoint = False)

array([10., 12., 14., 16., 18.])

In [15]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

###### That's all for now, there is much more to learn in numpy.
keep learning

# Great Job