# Numpy - Array Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

Boolean selection returns a view which authorize the modification of the original array

In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [4]:
#store all greater then 4 boolean values in a variable
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
#this will print the original values which is greater then 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
#if we just want to check where some values is greater or smaller
# we only used array with comparison operator and a comparing value
# array condition
arr>2


array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [7]:
#But we want to select all those values which meets our condition or which are True in above boolen values.
#we used- array[array condition]
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
names = np.array(['Mithilesh','Rohit', 'Deepak', 'Kishor', 'Rohit'])

In [10]:
#to get the boolean values
names =='Rohit'

array([False,  True, False, False,  True])

In [11]:
#to select those values

names[names=='Rohit']

array(['Rohit', 'Rohit'], dtype='<U9')

In [12]:
#to select all values which is not Rohit

names[names!='Rohit']

array(['Mithilesh', 'Deepak', 'Kishor'], dtype='<U9')

In [13]:
#check for either rohit or mithiliesh

(names=='Rohit')|(names=='Mithilesh')

array([ True,  True, False, False,  True])

In [14]:
#select all values which is either mithilesh or rohit
#and/or don’t work with Boolean array

names[(names=='Rohit')|(names=='Mithilesh')]


array(['Mithilesh', 'Rohit', 'Rohit'], dtype='<U9')

In [15]:
#select all values which is not rohit and assign  them as satish

names[names!='Rohit'] ='satish'

In [16]:
names

array(['satish', 'Rohit', 'satish', 'satish', 'Rohit'], dtype='<U9')

In [17]:
np.unique(names)

array(['Rohit', 'satish'], dtype='<U9')

###### That's all for now, there is much more to learn in numpy.
keep learning

# Great Job