# Numpy -Statistical Operation.

###### Vectorized Operations

In [1]:
import numpy as np

In [2]:
nums = np.arange(6)

In [3]:
#Multiplies each element by 10.

nums * 10


array([ 0, 10, 20, 30, 40, 50])

In [4]:
#Returns square root of each element.

nums = np.sqrt(nums)
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [5]:
#Floor, rint (round to nearest int)

np.ceil(nums)

array([0., 1., 2., 2., 2., 3.])

In [6]:
#Checks for NaN

np.isnan(nums) 

array([False, False, False, False, False, False])

In [7]:
#add element-wise

nums  + np.arange(6)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ,
       7.23606798])

In [8]:
 #Compare element wise
    
np.maximum(nums,np.array([1,-2,-3,-4,-5,-6])) 

array([1.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

###### Maths & Statistical Functions

In [9]:
#Random normals in 4x2 array.

rnd = np.random.randn(4,2)

In [10]:
rnd

array([[-0.17479188, -0.55407965],
       [-0.17939742, -1.42553483],
       [-0.5080219 ,  1.00295779],
       [ 0.48855794, -0.06864501]])

In [11]:
#Returns mean of  the array.

rnd.mean()

-0.17736936963160368

In [12]:
#Return Standard Diviation of the array.

rnd.std()

0.6761676833011296

In [13]:
#Returns the max value of an array.

rnd.max()

1.0029577874464324

In [14]:
#Returns index of max value of an array.

rnd.argmax()

5

In [15]:
#Returns min values of an array.

rnd.min()

-1.4255348347249877

In [16]:
#Returns index of min value of an array.

rnd.argmin()

3

In [17]:
#Returns sum of array.

rnd.sum()

-1.4189549570528295

In [18]:
#Returns sum of the column
rnd.sum(axis=0)

array([-0.37365325, -1.0453017 ])

In [19]:
#Returns sum of the row
rnd.sum(axis=1)

array([-0.72887153, -1.60493225,  0.49493589,  0.41991294])

###### Reshaping the arrays

In [20]:
#Returns a 2-dim, 8 x 4 array.

nums = np.arange(32).reshape(8,4)
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [21]:
#Returns a Transpose of an array

nums.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [22]:
#Returns a 1 dim array.

nums.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

###### Array Creation with Random Numbers

In [23]:
# random 3x3 matrix in [0to1]
np.random.rand(3,3)

array([[0.46325842, 0.54651472, 0.06543817],
       [0.98075671, 0.68556099, 0.86772114],
       [0.78091657, 0.89048586, 0.09710489]])

In [24]:
#random normal (mean 0, sd 1)
#randon 3x3 matrix [-1to1]

np.random.randn(3,3)

array([[-0.62711513, -0.34302839, -0.44646518],
       [ 0.90121964,  0.21997719, -0.79279062],
       [ 0.85354032,  0.92353531,  0.30752833]])

In [25]:
#9 randomly picked no. betn 0-4.

np.random.randint(0,5,9)

array([2, 2, 0, 1, 0, 0, 0, 2, 0])

###### Computing Euclidean Distance between 2 vectors.

In [26]:
vec1 = np.random.randn(10)
vec1

array([-0.42492992,  0.61023676,  0.74571317,  0.299786  , -1.22691053,
       -0.24911682, -0.078548  ,  0.8724014 , -0.69657034,  0.58179611])

In [27]:
vec2 = np.random.randn(10)
vec2

array([-0.44054214, -0.83497408, -1.39158898,  0.796215  , -0.15742537,
       -0.32963304,  0.16103407,  1.45510456,  0.13734419,  0.40401817])

In [28]:
dist = np.sqrt(np.sum(vec1 - vec2)**2)

In [29]:
dist

0.6343054629386059

###### That's all for now, there is much more to learn in numpy.
keep learning

# Great Job